inherit_from: .rubocop_todo.yml

Layout/HashAlignment:
  AllowMultipleStyles: true
  EnforcedColonStyle: key
AllCops:
  TargetRubyVersion: 2.4  # Pin to flagsmith.gemspec required_ruby_version
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*'
    - 'example/**/*'
    - 'vendor/**/*'
