# This workflow will build the gem from gemspec and publish

name: Push Ruby Gem

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # need all the commits
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Buld and Push to rubygems.org
        run: |
          bundle install
          gem build flagsmith.gemspec
          rake release[remote]
