# This workflow will build the gem from gemspec and publish

name: Push Ruby Gem

# TODO: this workflow doesn't work, needs fixing but for now, I've just changed it so
# it will only run if triggered manually. Instructions for releasing manually are here:
# https://www.notion.so/flagsmith/SDKs-Deployment-Instructions-c1190a22238a45af9a51c7f0fea27f99
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # need all the commits
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Buld and Push to rubygems.org
        run: |
          bundle install
          gem build flagsmith.gemspec
          bundle exec rake release[remote]
